<a href="https://colab.research.google.com/github/Valaybundele/SVM_implementation/blob/master/2linearSVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
from google.colab import files
uploaded = files.upload()

Saving balance-scale.csv to balance-scale (1).csv


In [0]:
import io
df2 = pd.read_csv(io.BytesIO(uploaded['balance-scale.csv']))

In [0]:
df2

R  1  1.1  1.2  2
0    R  1    1    1  3
1    R  1    1    1  4
2    R  1    1    1  5
3    R  1    1    2  1
4    R  1    1    2  2
..  .. ..  ...  ... ..
570  L  5    5    4  5
571  L  5    5    5  1
572  L  5    5    5  2
573  L  5    5    5  3
574  L  5    5    5  4

[575 rows x 5 columns]

In [0]:
df3=df2.replace(to_replace='R',value =1)



In [0]:
df4=df3.replace(to_replace='L', value=-1)

In [0]:
df4

R  1  1.1  1.2  2
0    1  1    1    1  3
1    1  1    1    1  4
2    1  1    1    1  5
3    1  1    1    2  1
4    1  1    1    2  2
..  .. ..  ...  ... ..
570 -1  5    5    4  5
571 -1  5    5    5  1
572 -1  5    5    5  2
573 -1  5    5    5  3
574 -1  5    5    5  4

[575 rows x 5 columns]

In [0]:
 import pandas as pd
 from sklearn.model_selection import train_test_split
 from sklearn.datasets import load_iris

In [0]:
 y=df4.R
 x=df4.drop('R',axis=1)

In [0]:
x


1  1.1  1.2  2
0    1    1    1  3
1    1    1    1  4
2    1    1    1  5
3    1    1    2  1
4    1    1    2  2
..  ..  ...  ... ..
570  5    5    4  5
571  5    5    5  1
572  5    5    5  2
573  5    5    5  3
574  5    5    5  4

[575 rows x 4 columns]

In [0]:
y

0      1
1      1
2      1
3      1
4      1
      ..
570   -1
571   -1
572   -1
573   -1
574   -1
Name: R, Length: 575, dtype: int64

In [0]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

1  1.1  1.2  2
447  4    5    3  2
437  4    5    1  2
241  3    1    4  1
290  3    3    4  3
261  3    2    3  3
..  ..  ...  ... ..
69   1    4    1  1
119  2    1    2  3
284  3    3    3  1
491  5    2    3  1
148  2    2    3  4

[460 rows x 4 columns]

In [0]:
x_train = x_train.rename_axis('ID').values*1.

print(x_train)

[[4. 5. 3. 2.]
 [4. 5. 1. 2.]
 [3. 1. 4. 1.]
 ...
 [3. 3. 3. 1.]
 [5. 2. 3. 1.]
 [2. 2. 3. 4.]]


In [0]:
y_train=y_train.rename_axis('ID').values*1.
print(y_train)

[-1. -1.  1.  1.  1. -1.  1. -1.  1.  1. -1. -1.  1. -1. -1. -1. -1. -1.
 -1.  1.  1. -1. -1. -1.  1. -1.  1. -1.  1. -1.  1.  1. -1.  1.  1.  1.
  1.  1. -1.  1.  1. -1. -1. -1. -1. -1.  1.  1. -1.  1. -1.  1. -1.  1.
  1. -1. -1.  1. -1.  1. -1. -1. -1. -1.  1.  1. -1. -1.  1.  1.  1. -1.
 -1.  1. -1.  1.  1. -1. -1. -1.  1.  1.  1.  1.  1.  1. -1.  1. -1. -1.
  1. -1. -1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1.  1. -1. -1.  1.  1.
 -1. -1.  1.  1. -1. -1. -1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1.  1.
 -1. -1. -1.  1. -1. -1. -1. -1.  1.  1. -1.  1.  1.  1.  1. -1.  1. -1.
 -1.  1.  1.  1.  1.  1.  1.  1. -1. -1.  1. -1. -1.  1.  1.  1.  1. -1.
 -1. -1. -1. -1.  1. -1. -1. -1. -1.  1.  1.  1. -1. -1. -1. -1. -1.  1.
  1. -1.  1.  1.  1. -1.  1. -1. -1.  1.  1. -1. -1. -1.  1.  1.  1. -1.
  1.  1. -1.  1.  1.  1.  1. -1. -1.  1. -1.  1.  1.  1.  1.  1. -1. -1.
  1.  1. -1.  1.  1.  1.  1. -1.  1. -1. -1.  1.  1.  1.  1.  1.  1.  1.
 -1.  1.  1.  1.  1.  1. -1.  1. -1.  1. -1.  1. -1

In [0]:
x_test = x_test.rename_axis('ID').values*1.

print(x_test)

[[4. 5. 1. 1.]
 [2. 4. 3. 5.]
 [4. 2. 5. 5.]
 [2. 4. 1. 3.]
 [3. 1. 3. 4.]
 [2. 4. 3. 2.]
 [1. 5. 3. 1.]
 [1. 1. 2. 1.]
 [1. 5. 3. 2.]
 [4. 3. 2. 2.]
 [1. 5. 5. 3.]
 [3. 5. 5. 4.]
 [4. 5. 1. 4.]
 [5. 2. 1. 5.]
 [2. 5. 5. 4.]
 [5. 5. 1. 1.]
 [2. 3. 5. 1.]
 [4. 1. 1. 1.]
 [3. 4. 5. 4.]
 [4. 5. 1. 3.]
 [5. 5. 5. 3.]
 [5. 1. 4. 2.]
 [2. 3. 3. 1.]
 [5. 1. 2. 5.]
 [4. 4. 2. 3.]
 [3. 2. 1. 3.]
 [3. 2. 2. 2.]
 [3. 1. 4. 2.]
 [1. 1. 4. 2.]
 [4. 1. 3. 5.]
 [3. 2. 5. 5.]
 [4. 3. 4. 1.]
 [4. 2. 1. 4.]
 [4. 3. 2. 5.]
 [5. 4. 5. 5.]
 [2. 2. 1. 1.]
 [1. 2. 1. 5.]
 [3. 4. 4. 1.]
 [1. 3. 3. 5.]
 [1. 5. 5. 2.]
 [1. 1. 3. 1.]
 [4. 3. 3. 2.]
 [5. 4. 1. 5.]
 [4. 1. 4. 3.]
 [5. 1. 3. 4.]
 [1. 5. 3. 4.]
 [3. 4. 3. 5.]
 [4. 4. 4. 1.]
 [2. 1. 1. 3.]
 [3. 3. 4. 2.]
 [4. 3. 4. 5.]
 [3. 1. 1. 1.]
 [4. 1. 2. 4.]
 [1. 5. 1. 4.]
 [4. 2. 1. 1.]
 [2. 4. 4. 4.]
 [4. 3. 5. 4.]
 [2. 4. 2. 1.]
 [2. 1. 3. 2.]
 [2. 2. 2. 1.]
 [3. 3. 1. 4.]
 [2. 5. 5. 5.]
 [5. 4. 3. 4.]
 [2. 3. 4. 1.]
 [1. 4. 2. 5.]
 [4. 4. 3. 3.]
 [5. 3. 1.

In [0]:
from cvxopt import matrix as cvxopt_matrix
from cvxopt import solvers as cvxopt_solvers
y_train = y_train.reshape(-1,1)*1. 

In [0]:
y_test = y_test.rename_axis('ID').values*1.

print(y_test)


[-1.  1.  1. -1.  1. -1. -1.  1.  1. -1.  1.  1. -1. -1.  1. -1. -1. -1.
  1. -1. -1.  1. -1.  1. -1. -1. -1.  1.  1.  1.  1. -1. -1. -1.  1. -1.
  1. -1.  1.  1.  1. -1. -1.  1.  1.  1.  1. -1.  1. -1.  1. -1.  1. -1.
 -1.  1.  1. -1.  1. -1. -1.  1. -1. -1.  1. -1. -1. -1. -1.  1. -1. -1.
  1. -1.  1.  1. -1. -1. -1. -1.  1.  1. -1. -1.  1. -1.  1. -1. -1. -1.
 -1.  1. -1. -1. -1. -1. -1. -1.  1.  1.  1.  1. -1.  1. -1. -1.  1. -1.
  1.  1.  1.  1. -1.  1.  1.]


In [0]:
y_test[0]

-1.0

In [0]:
y_train

array([[-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [-1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [ 1.],
       [ 1.],
       [ 1.],
      

In [0]:
C = 10

In [0]:
X_dash=y_train*x_train*1.


In [0]:
import numpy as np
H = np.dot((X_dash),(np.transpose(X_dash)))*1.

In [0]:
H

array([[ 54.,  48., -31., ...,  38.,  41., -35.],
       [ 48.,  46., -23., ...,  32.,  35., -29.],
       [-31., -23.,  27., ..., -25., -30.,  24.],
       ...,
       [ 38.,  32., -25., ...,  28.,  31., -25.],
       [ 41.,  35., -30., ...,  31.,  39., -27.],
       [-35., -29.,  24., ..., -25., -27.,  33.]])

In [0]:
P = cvxopt_matrix(H)
q = cvxopt_matrix(-np.ones((460, 1)))
G = cvxopt_matrix(np.vstack((np.eye(460)*-1,np.eye(460))))
h = cvxopt_matrix(np.hstack((np.zeros(460), np.ones(460) * C)))
A = cvxopt_matrix(y_train.reshape(1, -1))
b = cvxopt_matrix(np.zeros(1))

In [0]:
cvxopt_solvers.options['show_progress'] = False
cvxopt_solvers.options['abstol'] = 1e-10
cvxopt_solvers.options['reltol'] = 1e-10
cvxopt_solvers.options['feastol'] = 1e-10

In [0]:
sol = cvxopt_solvers.qp(P, q, G, h, A, b)
alphas = np.array(sol['x'])


In [0]:
w = ((y_train * alphas).T @ x_train).reshape(-1,1)
S = (alphas > 1e-4).flatten()
b = y_train[S] - np.dot(x_train[S], w)

#Display results
print('Alphas = ',alphas[alphas > 1e-4])
print('w = ', w.flatten())
print('b = ', b[0])


Alphas =  [ 0.03060658  0.03342542  0.03511828  0.03487031 10.          0.03254177
  0.56436068  5.7957937  10.          0.50221474  0.03706267 10.
  0.03028285 10.         10.          0.67841011 10.          0.04007596
  0.03275127 10.          0.04336971  1.10400074 10.          0.03702048
 10.          0.69597476 10.          0.57891177  0.03346112 10.
  0.46660313  0.03686824  0.6135018   0.8280482   1.21027205  0.72557885
 10.          0.03378473  0.74036905 10.          1.23813976  1.86011667
  0.88893363 10.          1.00084869 10.          0.03977321  0.03657905
  0.0321876   0.70859678  1.02898843  1.28874342  0.0330877  10.
 10.         10.          1.1762378   0.03075632  3.07583196 10.
  0.02970351  0.03260664  2.13666236  1.63814897  1.23889539 10.
  0.63199     0.04224257  0.0316245   0.48147613  0.03820326  0.03561943
  0.87112684  0.03447603  0.03545076  0.03911798  0.51476146 10.
  0.03876426  0.04205695  1.36438159  0.64549022  0.03115189 10.
  0.03167606  0.04862237

In [0]:
len(alphas)

460

In [0]:
for x in x_test :
   print((np.dot(np.transpose(x),w))[0])

-7.000000000123222
2.00000000003142
4.00000000006942
-2.0000000000386393
3.000000000050406
-1.0000000000161577
-2.0000000000318465
1.0000000000190141
-1.0000000000159872
-3.000000000053177
2.000000000038213
1.0000000000187157
-4.000000000075644
-1.00000000002494
2.000000000036394
-8.0000000001409
1.0000000000238316
-3.0000000000531912
2.0000000000362235
-5.000000000091504
-2.0000000000325002
2.5011104298755527e-12
-1.0000000000145093
1.0000000000117382
-3.0000000000548255
-1.000000000021302
-1.000000000017991
2.0000000000378577
4.000000000073214
3.000000000048587
5.000000000087098
-2.0000000000306954
-1.000000000023121
-5.5990767577895895e-12
1.0000000000167262
-2.0000000000353424
3.000000000045773
-2.000000000030525
4.000000000066606
1.0000000000223537
2.0000000000381846
-2.0000000000340066
-3.0000000000599556
2.0000000000360387
1.0000000000150493
1.0000000000157314
1.000000000013742
-3.000000000048203
1.000000000013884
2.8421709430404007e-12
2.000000000032742
-2.000000000035513
1.000

In [0]:
import numpy as np
predictedlabel=[]
predictedlabel = [None] * len(x_test)
i=0
for x in x_test :
  z=((np.dot(np.transpose(x),w))[0] + b[0])
  if z>0 :
    predictedlabel[i]=1;
    i=i+1;
  elif z<0 :
    predictedlabel[i]=-1;
    i=i+1
print(i)

count=0;
i=0;
while i < 115 :
  if predictedlabel[i]==y_test[i] :
     count=count+1;
  i=i+1;
print(count)
  
  






115
111
